FROM node:6.11-alpine

LABEL MAINTAINER "Dashlorde <zhouyunlu0216@gmail.com>"
LABEL MAINTAINER "Abdurrachman Mappuji <mappuji@ole.org>"
LABEL MAINTAINER "dogi <stefan@unterhauser.name>"

ENV version '0.13.21'

RUN mkdir -p /app/server/src

RUN apk add --update openssl && npm install express && \
    wget -O BeLL-Apps-${version}.tar.gz \
    https://github.com/open-learning-exchange/BeLL-Apps/archive/${version}.tar.gz && \
    tar xvf BeLL-Apps-${version}.tar.gz && \
    mv BeLL-Apps-${version}/* /app/server/src/ && \
    rm /app/server/src/package.json

WORKDIR /app/server/src

COPY server.js ./
COPY package.json ./

RUN chmod +x ./server.js && npm install

EXPOSE 80

CMD ["npm","start"]
